### ISSUE TITLE
example ghul.template build fails

### ISSUE THREAD

**Issue by quanglewangle** [degory/ghul#911]
peter@peter-ThinkPad-X220:~/ghul$ dotnet new --install ghul.templates
The following template packages will be installed:
   ghul.templates

ghul.templates is already installed, version: 0.2.1, it will be replaced with version .
ghul.templates::0.2.1 was successfully uninstalled.
Success: ghul.templates::0.2.1 installed the following templates:
Template Name               Short Name     Language  Tags   
--------------------------  -------------  --------  -------
ghūl class library package  ghul-classlib  ghūl      Console
ghūl console application    ghul-console   ghūl      Console

peter@peter-ThinkPad-X220:~/ghul$ mkdir my-console-project
peter@peter-ThinkPad-X220:~/ghul$ cd my-console-project
peter@peter-ThinkPad-X220:~/ghul/my-console-project$ dotnet new ghul-console
The template "ghūl console application" was created successfully.
peter@peter-ThinkPad-X220:~/ghul/my-console-project$ dotnet run
/home/peter/.nuget/packages/ghul.targets/1.0.0/build/ghul.targets.targets(71,5): error MSB3073: The command "dotnet ghul-compiler @.build.rsp" exited with code 1. [/home/peter/ghul/my-console-project/my-console-project.ghulproj]

The build failed. Fix the build errors and run again.

FYI - environment
peter@peter-ThinkPad-X220:~/ghul/my-console-project$ dotnet --list-sdks
5.0.101 [/home/peter/dotnet/sdk]
6.0.100 [/home/peter/dotnet/sdk]

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by degory** [comment]
The most likely cause is that local tools need restoring- the template includes a .NET tool manifest file, but the compiler won't actually be installed without a local tool restore:

The ghūl VSCode extension does a tool restore automatically (or should do) whenever a ghūl a project is opened, but there's nothing to do it automatically if you're doing the whole thing from the command line.

Looks like a possible fix would be to add a post install action to the templates (https://github.com/dotnet/templating/wiki/Post-Action-Registry). I will investigate.

@quanglewangle can you confirm that if you manually restore local tools, `dotnet run` then succeeds? (You should only need to restore the tools once after template instantiation):

```
dotnet tool restore
dotnet run
```

Alternatively if that doesn't work, can you .zip the folder up and attach to this bug?

**Comment by quanglewangle** [comment]
peter@peter-ThinkPad-X220:~/ghul/my-console-project$ dotnet tool restore
Tool 'ghul.compiler' (version '0.5.0') was restored. Available commands: ghul-compiler

Restore was successful.
peter@peter-ThinkPad-X220:~/ghul/my-console-project$ dotnet run
/home/peter/.nuget/packages/ghul.targets/1.0.0/build/ghul.targets.targets(71,5): error MSB3073: The command "dotnet ghul-compiler @.build.rsp" exited with code 1. [/home/peter/ghul/my-console-project/my-console-project.ghulproj]

The build failed. Fix the build errors and run again.

[bin.zip](https://github.com/degory/ghul/files/7794225/bin.zip)

**Comment by degory** [comment]
Couple of questions:
- Can you zip again including hidden folders?
- Is your `src/` folder actually empty?
Thanks

**Comment by degory** [comment]
OK, I can see you must have a source file in src/ because your out.il file has plausible IL in it.

It's tricky to tell what might be doing on because the .zip file is incomplete. Can you try tar instead:

```
tar cvzf project.tgz  my-console-project/
```

**Comment by quanglewangle** [comment]
git compains about tar file. Here is zip recursive dir one with  .*  Hope this will do.

[new.zip](https://github.com/degory/ghul/files/7794391/new.zip)
e

**Comment by degory** [comment]
Thanks.

I've created a clean Debian 10 VM, installed the .NET 6.0 SDK and the ghul project templates and I get a similar error if I do `dotnet run` without first doing a `dotnet tool restore`. However, for me, the tool restore then fixes the issue and doing 'dot net run' again works as expected.

Can you try the following:
```
dotnet nuget locals --clear all
mkdir test-project
cd test-project
dotnet new ghul-console
dotnet build /v:q >output.txt 2>&1
dotnet run
```

And, if it doesn't run successfully, attach `output.txt` to this bug

```

**Comment by quanglewangle** [comment]
peter@peter-ThinkPad-X220:~/ghul$ dotnet nuget locals --clear all
Clearing NuGet HTTP cache: /home/peter/.local/share/NuGet/v3-cache
Clearing NuGet global packages folder: /home/peter/.nuget/packages/
Clearing NuGet Temp cache: /tmp/NuGetScratch
Clearing NuGet plugins cache: /home/peter/.local/share/NuGet/plugins-cache
Local resources cleared.
peter@peter-ThinkPad-X220:~/ghul$ mkdir test-project
peter@peter-ThinkPad-X220:~/ghul$ cd test-project
peter@peter-ThinkPad-X220:~/ghul/test-project$ dotnet new ghul-console
The template "ghūl console application" was created successfully.
peter@peter-ThinkPad-X220:~/ghul/test-project$ dotnet tool restore
Tool 'ghul.compiler' (version '0.5.0') was restored. Available commands: ghul-compiler

Restore was successful.
peter@peter-ThinkPad-X220:~/ghul/test-project$ dotnet build /v:q >output.txt 2>&1
peter@peter-ThinkPad-X220:~/ghul/test-project$ dotnet run
/home/peter/.nuget/packages/ghul.targets/1.0.0/build/ghul.targets.targets(71,5): error MSB3073: The command "dotnet ghul-compiler @.build.rsp" exited with code 1. [/home/peter/ghul/test-project/test-project.ghulproj]

The build failed. Fix the build errors and run again.



[output.txt](https://github.com/degory/ghul/files/7794581/output.txt)

**Comment by degory** [comment]
Sorry, I garbled the command line. Can you try
```
dotnet build -v:d >output.txt 2>&1
``` 

Note `-v:d`

**Comment by quanglewangle** [comment]
Been back over what I have done and noticed I installed .NET 6.0.100 not 6.0.0 Hope that isn't the problem. Too late tonight but could try with 6.0.0 tomorrow

new output.txt
[output.txt](https://github.com/degory/ghul/files/7794636/output.txt)

**Comment by degory** [comment]
It is failing because it can't find the SDK. However, it's not the version (6.0.100 should be fine - I have the same version). The problem is that the SDK is not in the expected location (it's in your home directory rather than /usr/share)

The compiler actually only needs the SDK location in order extract the SDK version number and write it to the `.runtimeconfig.json` file. I will see if the SDK version or location is available to the MSBuild target - if so, I can just pass it in on the compiler command line.

You can probably work around this by creating a symbolic link from `/home/peter/dotnet` to `/usr/share/dotnet`

**Comment by degory** [comment]
Try upgrading the compiler tool in your test project by downloading + unzipping the attached NuGet package and then, from within the project folder, running

```
dotnet tool update ghul.compiler --version 0.5.1-beta.2 --add-source <path to folder containing the .nupkg>
```

[ghul.compiler.0.5.1-beta.2.zip](https://github.com/degory/ghul/files/7794767/ghul.compiler.0.5.1-beta.2.zip)

**Comment by quanglewangle** [comment]
I can confirm that  0.5.1-beta.2 fixes the issue.
