### ISSUE TITLE
ghul vs code extension fails on example projec 

### ISSUE THREAD

**Issue by quanglewangle** [degory/ghul#913]
output is
Request initialize failed with message: Command failed: dotnet tool restore
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'tool' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

SDK is installed
tried uninstall and reinstallexension

**Comment by degory** [comment]
The extension runs a couple of process on start-up - it attempts to restore local .NET tools and then it runs MSBuild to get the set of assemblies referenced by the project. It's using NodeJS execSync to do this, which just uses whatever PATH is set to in the VSCode process hosting the extension.

It looks like it's finding a `dotnet` executable, but that executable does know about the 'tool' command.

Can you try starting VSCode from the command line in a shell that definitely has the correct `dotnet` on the PATH?

Also, can you try starting a shell from within VSCode and see if `dotnet tool restore` works as expected and, if not, check the PATH?

**Comment by degory** [comment]
Actually, can you try this instrumented build of the VSCE, which will log the PATH, which `dotnet` is found on the PATH, and which SDKs are available. Open the extensions panel on the left of VSCode (Square with a small square hanging out the top) and then use the `...` menu at the top of that panel to `Install from VSIX...`. (Unzip the .zip file to get the .vsix)

[ghul-0.5.2.vsix.zip](https://github.com/degory/ghul/files/7796447/ghul-0.5.2.vsix.zip)

**Comment by quanglewangle** [comment]
Running vscode from command line runs without error
Seting PATH in .bash_profile to include dotnet location also allows vscode to start from KDE menu without error

I think my PATH setting may be screwed I have the same folders in the list several times

**Comment by degory** [comment]
Closing as was due to .NET SDK not being on the PATH rather than an issue with the example project.
