### ISSUE TITLE
No ilasm for Raspberry PI - Exec format error

### ISSUE THREAD

**Issue by quanglewangle** [degory/ghul#917]
/.nuget/packages/ghul.compiler/0.5.2/tools/net6.0/any/runtimes/ tree has linux-64 and win-x64 but no arm subtree

dotnet build
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  conditional-compilation count: 1 total time: 74.1437 average: 74.1437 moving average: 14.829 ms
  rewrite-syntax-trees count: 1 total time: 131.8122 average: 131.8122 moving average: 26.362 ms
  declare-symbols count: 1 total time: 133.4556 average: 133.4556 moving average: 26.691 ms
  resolve-uses count: 1 total time: 37.5631 average: 37.5631 moving average: 7.513 ms
  resolve-type-expressions count: 1 total time: 737.6346 average: 737.6346 moving average: 147.527 ms
  resolve-ancestors count: 1 total time: 14.5448 average: 14.5448 moving average: 2.909 ms
  resolve-explicit-types count: 1 total time: 17.8364 average: 17.8364 moving average: 3.567 ms
  resolve-overrides count: 1 total time: 27.0832 average: 27.0832 moving average: 5.417 ms
  compile-expressions count: 1 total time: 175.5136 average: 175.5136 moving average: 35.103 ms
  generate-il count: 1 total time: 128.3176 average: 128.3176 moving average: 25.664 ms
  System.ComponentModel.Win32Exception (8): An error occurred trying to start process /home/peter/.nuget/packages/ghul.compiler/0.5.2/tools/net6.0/any/runtimes/linux-x64/native/ilasm' with working directory /home/peter/ghul/my-console-project'. Exec format error
     at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
     at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
     at System.Diagnostics.Process.Start()
     at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
     at System.Diagnostics.Process.Start(String fileName, String arguments)
     at Driver.Main.finish_build_dotnet()
     at Driver.Main.finish_build()
     at Driver.Main..ctor(List`1 arguments)
  !!! failed !!!
/home/peter/.nuget/packages/ghul.targets/1.0.0/build/ghul.targets.targets(71,5): error MSB3073: The command "dotnet ghul-compiler @.build.rsp" exited with code 1. [/home/peter/ghul/my-console-project/my-console-project.ghulproj]

Build FAILED.

/home/peter/.nuget/packages/ghul.targets/1.0.0/build/ghul.targets.targets(71,5): error MSB3073: The command "dotnet ghul-compiler @.build.rsp" exited with code 1. [/home/peter/ghul/my-console-project/my-console-project.ghulproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:11.97

**Comment by degory** [comment]
There are a couple of underlying problems:

1. [ ] the code that calls the assembler assumes all Linux systems are 64-bit x86: 
https://github.com/degory/ghul/blob/0c2e06124ed658803df67ed124a0f572d2e11f81/src/driver/path_config.ghul#L48-L54
This one is easy enough to fix - just need to check `RuntimeInformation.ProcessArchitecture` for ARM vs x86 and possibly something similar for 32bit vs 64bit

2. [ ] I'm already packaging two copies of ILAsm, and supporting both 32-bit and 64-bit ARM for the PI would add two more:
https://github.com/degory/ghul/blob/0c2e06124ed658803df67ed124a0f572d2e11f81/ghul.ghulproj#L53-L54

I suspect I'm not referencing the IL assembler correctly, but there are not a lot of examples of how to do this as it's hardly a common use case. It might be that I'm supposed to be referencing the non-architecture specific version of the package (see https://www.nuget.org/packages/Microsoft.NETCore.ILAsm/). I'll investigate.

**Comment by degory** [comment]
My requirements are:

1. I want a user to be able to create a new ghūl project or clone a ghūl repository and immediately build it, without having to manually install any dependencies or perform any manual steps beyond what would be expected for any .NET SDK project.

2. I'd prefer to have the compiler version embedded in the project/repository, as this means I can make breaking changes and projects can be updated on their own schedules.

3. I want any reference to the compiler baked into projects/repositories to be agnostic as to host environment 

4. I don't really want to package 4+MB of IL assembler binaries (2 OSs x 2 address sizes x 2 ISAs x 0.5MB+ per binary) into the compiler

Not having requirement 2 breaks requirement 1 - I'm not aware of any way to have the compiler as a globally installed dependency that is transparently restored by the .NET SDK build processes

Not having requirement 3 also breaks requirement 1 - if a repository depends on a specific architecture/OS/address width of the IL assembler, then that means manual setup for anyone cloning it to adjust to their own host environment, plus they need to remember not to push those changes upstream (assuming requirement 2)

If I remove requirements 1 + 2, I can have the CI process package 8 versions of the compiler and direct users to install the appropriate one for their host. I can see having so many versions being confusing though.

Alternatively if I remove requirement 4 and just bundle all 8 versions of the assembler, I can meet all the other requirements and I guess a 4MB package is not a huge deal in the grand scheme of things

**Comment by degory** [comment]
Decided to compromise and continue to bundle IL assembler binaries in the compiler tool package only for the most common hosts (Windows + Linux 64-bit x86). Added support for additional hosts via explicit IL assembler package reference in `.ghulproj`.

For example, to support compilation on Linux ARM64, you could add the following to an `<ItemGroup>` in your `.ghulproj` file:
```
<PackageReference Include="runtime.linux-arm64.Microsoft.NETCore.ILAsm" Version="6.0.0" GeneratePathProperty="true" />
```

(Note `GeneratePathProperty="true"` is needed so the compile target can find the IL assembler package files)

All hosts with a suitable IL assembler package should be supported via this mechanism
