### ISSUE TITLE
System.Data.Common.DbDataReader.get_Item() not completely translated to snake case

### ISSUE THREAD

**Issue by quanglewangle** [degory/ghul#936]
In code completion menu System.Data.Common.DbDataReader.get_Item(ordinal: Ghul.int) is presented not completely translated to snake case. Note uppercase "I"

This doesn't seem to cause a problem but changing "I" to "i" causes  "member get_item not found in System.Data.Common.DbDataReader " error.

**Comment by degory** [comment]
`get_Item()` is special - in C# it maps to an indexer and in ghul it should do the same - it ought to appear as `[ordinal: Ghul.int]: object`, but the code completer doesn't understand indexers.

Despite the completer not showing it correctly, it ought to be possible to call it using indexer syntax:
```
let dr: DbDataReader = ...

let o = dr[1];
```
