### ISSUE TITLE
string equality compare returns false for "date"

### ISSUE THREAD

**Issue by quanglewangle** [degory/ghul#937]
rdr.get_data_type_name(i) == "date" 
evaluates to  false even when rdr.get_data_type_name(i) is returning "date"
Works ok for "bigint" and "character varying" ie evaluates true when expected.

`namespace Test is
    use Npgsql;

    class Main is 
        entry() static is            
            var psqlInfo = "Host=localhost;Port=5432;Database=testdb; " +
            " Username=dbuser;Password=password";

            var con = new Npgsql.NpgsqlConnection(psqlInfo);

            con.open();
            var sql = "SELECT * FROM transactions";
            var cmd = new NpgsqlCommand(sql, con);

            var rdr = cmd.execute_reader();
            while rdr.read() do
                for i in 0 .. rdr.field_count do

                    if rdr.get_data_type_name(i) == "bigint" then
                        IO.Std.out.write_line( rdr.get_int64(i));

                    elif rdr.get_data_type_name(i) == "date" then
                        IO.Std.out.write_line( rdr.get_date_time(i));

                    elif rdr.get_data_type_name(i) == "character varying" then
                        IO.Std.out.write_line( rdr.get_string(i));
                    
                    else  
                        IO.Std.out.write( " no match for ");
                        IO.Std.out.write_line (">" + rdr.get_data_type_name(i) + "<");  
                    fi
                od
            od
        si
    si   
si

`

**Comment by degory** [comment]
Apologies, I've only just noticed this.

This is expected behavior: for reference types, `==` compares references not values. You need to use `=~` / `!~` (value equals/value not-equals)

**Comment by quanglewangle** [comment]
Thanks for the clarification
Peter
