### ISSUE TITLE
dotnet build fails after update to 0.5.14

### ISSUE THREAD

**Issue by quanglewangle** [degory/ghul#946]
after doing
dotnet tool update ghul.compiler
and
dotnet clean

dotnet build fails with
/usr/share/dotnet/sdk/6.0.200/Microsoft.Common.CurrentVersion.targets(4650,5): error : Expected file "obj/Debug/net6.0/refint/acker.dll" does not exist. [/home/peter/ghul/acker/acker.ghulproj]

This is as example - is the same for all examples.  Examples did not exhibit this behavior before update

**Comment by degory** [comment]
This is caused by a breaking change in the .NET SDK 6.0.200. If you update ghul.targets to the latest version, it should fix it
